/* This file was generated by SableCC ( http://sablecc.org ). */

package language_enum;

public class NEnum_Enum
    extends NEnum {

  private final int line;
  private final int pos;
  private final N$0 e$0;
  private final N$1 e$1;
  private final NId eId;
  private final NEolHelper eEolHelper;
  private final NValues eValues;
  private final N$2 e$2;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inEnum_Enum(this);
    walker.caseEnum_Enum(this);
    walker.outEnum_Enum(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.e$0.apply(walker);
    this.e$1.apply(walker);
    this.eId.apply(walker);
    this.eEolHelper.apply(walker);
    this.eValues.apply(walker);
    this.e$2.apply(walker);
  }

  NEnum_Enum(int line, int pos, N$0 p$0, N$1 p$1, NId pId, NEolHelper pEolHelper, NValues pValues, N$2 p$2) {
    this.line = line;
    this.pos = pos;
    this.e$0 = p$0;
    this.e$1 = p$1;
    this.eId = pId;
    this.eEolHelper = pEolHelper;
    this.eValues = pValues;
    this.e$2 = p$2;
  }

  @Override
  public Type getType() {
    return Type.T_Enum_Enum;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Enum;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Enum_Enum;
  }

  public NId get_Id() {
    return this.eId;
  }

  public NEolHelper get_EolHelper() {
    return this.eEolHelper;
  }

  public NValues get_Values() {
    return this.eValues;
  }

  N$0 internalGet$0() {
    return this.e$0;
  }

  N$1 internalGet$1() {
    return this.e$1;
  }

  NId internalGetId() {
    return this.eId;
  }

  NEolHelper internalGetEolHelper() {
    return this.eEolHelper;
  }

  NValues internalGetValues() {
    return this.eValues;
  }

  N$2 internalGet$2() {
    return this.e$2;
  }
}
