/* This file was generated by SableCC ( http://sablecc.org ). */

package language_enum;

public class NEolHelper
    extends Token {

  public NEolHelper(String text, int line, int pos) {
    super(text, line, pos);
  }

  @Override
  public Type getType() {
    return Type.T_EolHelper;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_EolHelper;
  }

  @Override
  public void apply(Walker walker) {
    walker.inEolHelper(this);
    walker.caseEolHelper(this);
    walker.outEolHelper(this);
  }
}
