/* This file was generated by SableCC ( http://sablecc.org ). */

package language_enum;

public abstract class Node {

  public abstract Type getType();

  public static enum Type {
    T_Id,
    T_EolHelper,
    T_Enum_Enum,
    T_Values_Many,
    T_Values_One,
    T_Value_With,
    T_Value_Without,
    TEnd,
    TAnonymous;
  }

  public abstract ProductionType getProductionType();

  public static enum ProductionType {
    T_$Start,
    T_Enum,
    T_Values,
    T_Value,
    TNotAProduction;
  }

  public abstract String getText();
  public abstract int getLine();
  public abstract int getPos();
  public abstract void apply(Walker walker);
  public abstract void applyOnChildren(Walker walker);

  private Node parent;

  public Node getParent() {
    return this.parent;
  }

  void setParent(Node parent) {
    this.parent = parent;
  }

  @Override
  public String toString() {
    return "\"" + getText() + "\"@(" + getLine() + "," + getPos() + ")";
  }

  abstract InternalType getInternalType();

  static enum InternalType {
    T_$0,
    T_$1,
    T_Id,
    T_EolHelper,
    T_$2,
    T_$3,
    T_$Start,
    T_Enum_Enum,
    T_Values_Many,
    T_Values_One,
    T_Value_With,
    T_Value_Without,
    TEnd;
  }
}
