/* This file was generated by SableCC ( http://sablecc.org ). */

package language_enum;

public class NValues_Many
    extends NValues {

  private final int line;
  private final int pos;
  private final NValues eValues;
  private final NValue eValue;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inValues_Many(this);
    walker.caseValues_Many(this);
    walker.outValues_Many(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eValues.apply(walker);
    this.eValue.apply(walker);
  }

  public NValues_Many(int line, int pos, NValues pValues, NValue pValue) {
    this.line = line;
    this.pos = pos;
    this.eValues = pValues;
    this.eValue = pValue;
  }

  @Override
  public Type getType() {
    return Type.T_Values_Many;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Values;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Values_Many;
  }

  public NValues get_Values() {
    return this.eValues;
  }

  public NValue get_Value() {
    return this.eValue;
  }

  NValues internalGetValues() {
    return this.eValues;
  }

  NValue internalGetValue() {
    return this.eValue;
  }
}
