/* This file was generated by SableCC ( http://sablecc.org ). */

package language_enum;

public class NValues_One
    extends NValues {

  private final int line;
  private final int pos;
  private final NValue eValue;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inValues_One(this);
    walker.caseValues_One(this);
    walker.outValues_One(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eValue.apply(walker);
  }

  public NValues_One(int line, int pos, NValue pValue) {
    this.line = line;
    this.pos = pos;
    this.eValue = pValue;
  }

  @Override
  public Type getType() {
    return Type.T_Values_One;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Values;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Values_One;
  }

  public NValue get_Value() {
    return this.eValue;
  }

  NValue internalGetValue() {
    return this.eValue;
  }
}
