/* This file was generated by SableCC ( http://sablecc.org ). */

package language_enum;

public class NValue_Without
    extends NValue {

  private final int line;
  private final int pos;
  private final NId eId;
  private final NEolHelper eEolHelper;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.inValue_Without(this);
    walker.caseValue_Without(this);
    walker.outValue_Without(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
    this.eId.apply(walker);
    this.eEolHelper.apply(walker);
  }

  public NValue_Without(int line, int pos, NId pId, NEolHelper pEolHelper) {
    this.line = line;
    this.pos = pos;
    this.eId = pId;
    this.eEolHelper = pEolHelper;
  }

  @Override
  public Type getType() {
    return Type.T_Value_Without;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Value;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Value_Without;
  }

  public NId get_Id() {
    return this.eId;
  }

  public NEolHelper get_EolHelper() {
    return this.eEolHelper;
  }

  NId internalGetId() {
    return this.eId;
  }

  NEolHelper internalGetEolHelper() {
    return this.eEolHelper;
  }
}
