/* This file was generated by SableCC ( http://sablecc.org ). */

package language_enum;

class S_16
    extends TransitionState {

  static final S_16 instance = new S_16();

  private S_16() {
  }

  void setMarker(Lexer lexer) {
  }

  State getTarget(Symbol symbol) {
    switch(symbol) {
    case Symbol_min:
      return S_17.instance;
    case Symbol_9:
      return S_17.instance;
    case Symbol_10:
      return S_17.instance;
    case Symbol_13:
      return S_17.instance;
    case Symbol_32:
      return S_17.instance;
    case Symbol__0:
      return S_6.instance;
    case Symbol_61:
      return S_17.instance;
    case Symbol__d:
      return S_6.instance;
    case Symbol__e:
      return S_6.instance;
    case Symbol__m:
      return S_6.instance;
    case Symbol__n:
      return S_6.instance;
    case Symbol__u:
      return S_6.instance;
    case Symbol_end:
      return S_17.instance;
    default:
      return null;
    }
  }

}
