/* This file was generated by SableCC ( http://sablecc.org ). */

package language_enum;

class S_17
    extends FinalState {

  static final S_17 instance = new S_17();

  private S_17() {
  }

  Token getToken(Lexer lexer) {
    String text = lexer.accept(1);
    int line = lexer.getAcceptLine();
    int pos = lexer.getAcceptPos();

    return new N$0(text, line, pos);
  }
}
