/* This file was generated by SableCC ( http://sablecc.org ). */

package language_enum;

abstract class State {

  enum StateType {
    TRANSITION,
    FINAL;
  }

  abstract StateType getStateType();
}
