/* This file was generated by SableCC ( http://sablecc.org ). */

package language_enum;

enum Symbol {
  Symbol_min,
  Symbol_9,
  Symbol_10,
  Symbol_13,
  Symbol_32,
  Symbol_34,
  Symbol_61,
  Symbol__d,
  Symbol__e,
  Symbol__m,
  Symbol__n,
  Symbol__u,
  Symbol_end;

  static Symbol getSymbol(char c) {
    switch(c) {
    case 9: return Symbol_9;
    case 10: return Symbol_10;
    case 13: return Symbol_13;
    case 32: return Symbol_32;
    case 33: return Symbol_min;
    case 34: return Symbol_34;
    case 39: return Symbol_34;
    case 61: return Symbol_61;
    case 95: return Symbol_34;
    case 96: return Symbol_min;
    case 100: return Symbol__d;
    case 101: return Symbol__e;
    case 109: return Symbol__m;
    case 110: return Symbol__n;
    case 117: return Symbol__u;
    default:
      if(c <= 8) {
        return Symbol_min;
      }
      if(c >= 123) {
        return Symbol_min;
      }
      if(c >= 11 && c <= 12) {
        return Symbol_min;
      }
      if(c >= 14 && c <= 31) {
        return Symbol_min;
      }
      if(c >= 35 && c <= 38) {
        return Symbol_min;
      }
      if(c >= 40 && c <= 47) {
        return Symbol_min;
      }
      if(c >= 48 && c <= 57) {
        return Symbol_34;
      }
      if(c >= 58 && c <= 60) {
        return Symbol_min;
      }
      if(c >= 62 && c <= 64) {
        return Symbol_min;
      }
      if(c >= 65 && c <= 90) {
        return Symbol_34;
      }
      if(c >= 91 && c <= 94) {
        return Symbol_min;
      }
      if(c >= 97 && c <= 99) {
        return Symbol_34;
      }
      if(c >= 102 && c <= 108) {
        return Symbol_34;
      }
      if(c >= 111 && c <= 116) {
        return Symbol_34;
      }
      if(c >= 118 && c <= 122) {
        return Symbol_34;
      }
    }

    return null;
  }
}
