/* This file was generated by SableCC ( http://sablecc.org ). */

package language_enum;

public class Walker {

  public void inId(NId node) {
    defaultIn(node);
  }

  public void inEolHelper(NEolHelper node) {
    defaultIn(node);
  }

  public void inEnum_Enum(NEnum_Enum node) {
    defaultIn(node);
  }

  public void inValues_Many(NValues_Many node) {
    defaultIn(node);
  }

  public void inValues_One(NValues_One node) {
    defaultIn(node);
  }

  public void inValue_With(NValue_With node) {
    defaultIn(node);
  }

  public void inValue_Without(NValue_Without node) {
    defaultIn(node);
  }

  public void defaultIn(Node node) {
  }

  public void caseId(NId node) {
    defaultCase(node);
  }

  public void caseEolHelper(NEolHelper node) {
    defaultCase(node);
  }

  public void caseEnum_Enum(NEnum_Enum node) {
    defaultCase(node);
  }

  public void caseValues_Many(NValues_Many node) {
    defaultCase(node);
  }

  public void caseValues_One(NValues_One node) {
    defaultCase(node);
  }

  public void caseValue_With(NValue_With node) {
    defaultCase(node);
  }

  public void caseValue_Without(NValue_Without node) {
    defaultCase(node);
  }

  public void defaultCase(Node node) {
    node.applyOnChildren(this);
  }

  public void outId(NId node) {
    defaultOut(node);
  }

  public void outEolHelper(NEolHelper node) {
    defaultOut(node);
  }

  public void outEnum_Enum(NEnum_Enum node) {
    defaultOut(node);
  }

  public void outValues_Many(NValues_Many node) {
    defaultOut(node);
  }

  public void outValues_One(NValues_One node) {
    defaultOut(node);
  }

  public void outValue_With(NValue_With node) {
    defaultOut(node);
  }

  public void outValue_Without(NValue_Without node) {
    defaultOut(node);
  }

  public void defaultOut(Node node) {
  }
}
